services:
  timescaledb:
    image: timescale/timescaledb-ha:pg17
    hostname: timescaledb
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=xmen
      - POSTGRES_USER=x-men-user
      - POSTGRES_PASSWORD=x-men-password
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    hostname: pgadmin
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@localmind.com
      - PGADMIN_DEFAULT_PASSWORD=admin!#2026
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - timescaledb


  qdrant:
    image: qdrant/qdrant:latest
    hostname: qdrant
    container_name: qdrant
    ports:
      - "6333:6333" # REST
      - "6334:6334" # gRPC (required by Qdrant .NET client)
    volumes:
      - qdrant_data:/qdrant/data

  # prometheus:
  #   image: prom/prometheus
  #   container_name: prometheus
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #     - prometheus-data:/prometheus
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #     - '--storage.tsdb.path=/prometheus'
  #     - '--web.console.libraries=/usr/share/prometheus/console_libraries'
  #     - '--web.console.templates=/usr/share/prometheus/consoles'
  #     - '--web.enable-remote-write-receiver'

  # loki:
  #   image: grafana/loki:latest
  #   container_name: loki
  #   ports:
  #     - "3100:3100"
  #   volumes:
  #     - loki-data:/loki
  #   # command: -config.file=/etc/loki/local-config.yaml

  # grafana:
  #   environment:
  #     - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
  #     - GF_AUTH_ANONYMOUS_ENABLED=true
  #     - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
  #     - GF_FEATURE_TOGGLES_ENABLE=alertingSimplifiedRouting,alertingQueryAndExpressionsStepMode
  #   entrypoint:
  #     - sh
  #     - -euc
  #     - |
  #       mkdir -p /etc/grafana/provisioning/datasources
  #       cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
  #       apiVersion: 1
  #       datasources:
  #       - name: Loki
  #         type: loki
  #         access: proxy 
  #         orgId: 1
  #         url: http://loki:3100
  #         basicAuth: false
  #         isDefault: false
  #         version: 1
  #         editable: true
  #       - name: Prometheus
  #         type: prometheus
  #         access: proxy 
  #         orgId: 1
  #         url: http://prometheus:9090
  #         basicAuth: false
  #         isDefault: true
  #         version: 1
  #         editable: true
  #       EOF
  #       /run.sh
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   ports:
  #     - "3000:3000"

volumes:
  qdrant_data:
  # prometheus-data:
  # loki-data:
  postgres-data:
  pgadmin_data: