services:
  # timescaledb:
  #   image: timescale/timescaledb-ha:pg17
  #   hostname: timescaledb
  #   container_name: timescaledb
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_DB=
  #     - POSTGRES_USER=
  #     - POSTGRES_PASSWORD=
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data

  # pgadmin:
  #   image: dpage/pgadmin4
  #   hostname: pgadmin
  #   container_name: pgadmin
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=
  #     - PGADMIN_DEFAULT_PASSWORD=
  #   ports:
  #     - "5050:80"
  #   volumes:
  #     - pgadmin_data:/var/lib/pgadmin
  #   depends_on:
  #     - timescaledb


  qdrant:
    image: qdrant/qdrant:latest
    hostname: qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/data

volumes:
  qdrant_data:
  # postgres-data:
  # pgadmin_data: