apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    uid: tempo
    url: http://tempo:3200
    isDefault: true
    jsonData:
      httpMethod: GET
      tracesQuery:
        timeShiftEnabled: true
      nodeGraph:
        enabled: true
      streamingEnabled:
        search: true
